#!/bin/sh 


# BSPWM CONFIG

bspc config click_to_focus none
bspc config focus_follows_pointer on
bspc monitor --reset-desktops $(seq 1 9) 'Scratchpad'

bspc rule --add Emacs state=tiled

export _JAVA_AWT_WM_NONREPARENTING=1
# Startup Programs

for f in /etc/X11/xinit/xinitrc.d/*; do
  if [ -x "$f" ]; then
    "$f" &
  fi
done

setxkbmap -option compose:ralt

start_programs () {
actual_border_width=$(bspc config border_width)

bspc config border_width 0

xsetroot -cursor_name left_ptr
systemctl --user start pulseaudio.service

if [ -f "${HOME}/.keypw" ]; then
  keepassxc --config "$(realpath ${HOME}/.config/keepassxc/keepassxc.ini)" --pw-stdin "${HOME}/Passwords.kdbx" <"${HOME}/.keypw" &
fi

dex -a &
dex -a -s ${HOME}/.config/bspwm/autostart &
kdeconnect-indicator &

systemctl --user start window-manager.target 

picom -b --config ${HOME}/.config/picom/config &>/dev/null &

target=laptop
if [ $(hostname) == "elektra" ]; then
target=workstation
fi

polybar $target &>/dev/null & 
}

start_programs &> /tmp/bspwm_startup.log
unset start_programs

bspc config border_width $actual_border_width
