#!/bin/sh

# BSPWM CONFIG

bspc config click_to_focus none
bspc config focus_follows_pointer on

# Startup Programs

xsetroot -cursor_name left_ptr

systemctl --user start window-manager.target

if [ -f "${HOME}/.fehbg" ]; then
	${HOME}/.fehbg
fi

sxhkd &

picom -b --config ${HOME}/.config/picom/config &>/dev/null &

target=laptop
if [ $(hostname) == "elektra" ]; then
target=workstation
fi

polybar $target &>/dev/null &
